### PR TITLE
feat: smoking test

### PR DESCRIPTION
**Pull request by IceCodeNew**

### CODE REVIEW

**Comment by mzz2017** [comment]
Nice catch! Thank you!

**Comment by IceCodeNew** [comment]
https://github.com/mzz2017/gg/actions/runs/3059736173/jobs/4937459525
image

@mzz2017 这就是我希望添加冒烟测试的原因，我从 GitHub releases 下载最新的二进制以后，运行时遇到 segmentation fault 错误了
怀疑最近一次的 commit 导致了这个 bug

**Comment by IceCodeNew** [comment]
image

**Comment by mzz2017** [comment]
稍等，在看了在看了

**Comment by mzz2017** [comment]
https://github.com/mzz2017/gg/actions/runs/3060063612/jobs/4938146230 https://github.com/mzz2017/gg/commit/5dd0fc94a85bf870fc970a425b08c68c66fa8548
It seems passed.

**Comment by IceCodeNew** [comment]
> [mzz2017/gg/actions/runs/3060063612/jobs/4938146230](https://github.com/mzz2017/gg/actions/runs/3060063612/jobs/4938146230) [5dd0fc9](https://github.com/mzz2017/gg/commit/5dd0fc94a85bf870fc970a425b08c68c66fa8548) It seems passed.

嗯，是的，我也正要提同样的 PR。

**Pull request merged**
